### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by j6k4m8** [jwoglom/remarkable-substack#1]
Hi @jwoglom! Awesome work here. I was working on an rmapi wrapper very similar to yours and took a few "hints" from your `remarkable.py`. I'm wondering if you have a license or reuse policy in mind for this codebase? I do not want to reuse without your permission! I'm not planning on selling or commercializing or anything, but I want to be a good custodian of your awesome open work :)

(I usually like to license under Apache 2.0 or MIT licenses, if you're looking for options!)

**Comment by jwoglom** [comment]
Hi @j6k4m8, added a MIT license. Thanks.

**Comment by j6k4m8** [comment]
Super awesome. Thanks!
